version: "1"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - APP_DB_HOST=db
      - APP_DB_USER=root
      - APP_DB_PASSWD=my-secret-pw
      - APP_DB_NAME=activities
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=activities